# Generated by Django 4.1.7 on 2023-03-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='img',
            field=models.ImageField(default='mykey', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
